spring.application.name=expense_gateway

# Dynamic port for Render
server.port=${PORT:8080}


# Eureka server
eureka.client.service-url.defaultZone=https://admin:admin123@eurekadiscoveryserver.onrender.com/eureka/

# Gateway Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always

spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.discovery.locator.lower-case-service-id=false

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

