spring.application.name=expense_gateway

# Dynamic port for Render
server.port=${PORT:8080}


# Eureka server
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:https://admin:admin123@eurekadiscoveryserver.onrender.com/eureka/}
eureka.client.service-url.register-with-eureka= true
eureka.client.service-url.fetch-registry= true

# Gateway Routes
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=expense-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://EXPENSE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/expenses/**

spring.cloud.gateway.server.webflux.routes[2].id=help-support
spring.cloud.gateway.server.webflux.routes[2].uri=lb://HELPSUPPORT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/support/**

management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.discovery.locator.lower-case-service-id=false

# Global CORS configuration for Spring Cloud Gateway
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=https://help-dashboard.onrender.com
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

